### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by M1keMcM**

### CODE REVIEW

**Comment by atareao** [comment]
@michael-strath Thanks!!!!

**Review by atareao — COMMENTED** [review]
Thanks!!!

**Comment by M1keMcM** [comment]
no problem :)

great extension

**Comment by M1keMcM** [comment]
Might I suggest adding the winner of the games when there is a penalty shootout?

The api current match endpoint has a winner (and winner code) field so you could use this in conjunction with the stage_name field so that people can see who won when a knockout stage match goes to penalties :) I don't have the free time to give this a go at the moment unfortunately.

**Pull request merged**
